# permissions for end users to view maintenancewindows.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: maintenance-window
    app.kubernetes.io/managed-by: kustomize
  name: maintenancewindow-viewer-role
rules:
- apiGroups:
  - maintenanceoperator.io.maintenanceoperator.io
  resources:
  - maintenancewindows
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - maintenanceoperator.io.maintenanceoperator.io
  resources:
  - maintenancewindows/status
  verbs:
  - get
