---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - maintenance.custom.io.maintenence-window.io
  resources:
  - deployments
  - maintenancewindows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - maintenance.custom.io.maintenence-window.io
  resources:
  - deployments/status
  verbs:
  - get
- apiGroups:
  - maintenance.custom.io.maintenence-window.io
  resources:
  - maintenancewindows/finalizers
  verbs:
  - update
- apiGroups:
  - maintenance.custom.io.maintenence-window.io
  resources:
  - maintenancewindows/status
  verbs:
  - get
  - patch
  - update
